[mypy]
python_version = 3.13
warn_return_any = True
warn_unused_configs = True

[mypy-numpy.*]
ignore_missing_imports = True

[mypy-scipy.*]
ignore_missing_imports = True

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-altair.*]
ignore_missing_imports = True

[mypy-altair_saver.*]
ignore_missing_imports = True

[mypy-plotly.*]
ignore_missing_imports = True

[mypy-bs_python_utils.*]
ignore_missing_imports = True

[mypy-plotly.express.*]
ignore_missing_imports = True